server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer-service/**
          filters:
            - RewritePath=/customer-service/(?<segment>.*), /${segment}
            - PreserveHostHeader
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 100
            - name: StripPrefix
              args:
                parts: 1
            - RemoveRequestHeader=Cookie
            - AddRequestHeader=X-Gateway, Gateway

        - id: customer-service-api-docs
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/v3/api-docs/customer-service
          filters:
            - SetPath=/v3/api-docs

        - id: farm-service
          uri: lb://FARM-SERVICE
          predicates:
            - Path=/farm-service/**
          filters:
            - RewritePath=/farm-service/(?<segment>.*), /${segment}
            - PreserveHostHeader
            - name: StripPrefix
              args:
                parts: 1
            - AddRequestHeader=X-Gateway, Gateway

        - id: farm-service-api-docs
          uri: lb://farm-service
          predicates:
            - Path=/v3/api-docs/farm-service
          filters:
            - SetPath=/v3/api-docs

        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/booking-service/**
          filters:
            - RewritePath=/booking-service/(?<segment>.*), /${segment}
            - PreserveHostHeader
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 300
            - name: StripPrefix
              args:
                parts: 1

        - id: booking-service-api-docs
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/v3/api-docs/booking-service
          filters:
            - SetPath=/v3/api-docs

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 50
            - name: StripPrefix
              args:
                parts: 1

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notify/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 150
            - name: StripPrefix
              args:
                parts: 1
        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/delivery/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 150
            - name: StripPrefix
              args:
                parts: 1

        - id: delivery-service-api-docs
          uri: lb://delivery-service
          predicates:
            - Path=/v3/api-docs/delivery-service
          filters:
            - SetPath=/v3/api-docs

        - id: rating-service
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/rating/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 150
                redis-rate-limiter.burstCapacity: 300
            - name: StripPrefix
              args:
                parts: 1

        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 250
                redis-rate-limiter.burstCapacity: 300
            - name: StripPrefix
              args:
                parts: 1

      # âœ… These apply globally to all routes
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=X-Gateway, Passed

      httpclient:
        wiretap: true
        connect-timeout: 5000
        response-timeout: 15s

      forwarded:
        enabled: true

      codec:
        max-in-memory-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: Customer Service
        url: /v3/api-docs/customer-service
      - name: Booking Service
        url: /v3/api-docs/booking-service
      - name: Farm Service
        url: /v3/api-docs/farm-service
      - name: Delivery Service
        url: /v3/api-docs/delivery-service
      - name: Notification Service
        url: /v3/api-docs/notification-service
      - name: Payment Service
        url: /v3/api-docs/payment-service
      - name: Rating Service
        url: /v3/api-docs/rating-service
      - name: Admin Service
        url: /v3/api-docs/admin-service
